# Generated by Django 3.1.7 on 2021-03-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=64)),
                ('eng_code', models.CharField(max_length=64)),
                ('ch_name', models.CharField(max_length=64)),
            ],
        ),
    ]
